server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: planning-service
          uri: lb://PLANNING-SERVICE
          predicates:
            - Path=/api/plannings/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**

        - id: vehicle-service
          uri: lb://VEHICLE-SERVICE
          predicates:
            - Path=/api/vehicles/**

        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
