server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    wait-time-in-ms-between-sync-retries: 0
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0   # capture all requests (for learning)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
