server:
  port: 8081

spring:
  application:
    name: planning-service

  datasource:
    url: jdbc:mysql://localhost:3306/planning_db
    username: root
    password: root   # change if needed

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  leve.org.springframework.data.jpa.repository: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0   # capture all requests (for learning)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

resilience4j:
  circuitbreaker:
    instances:
      order-service:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s        

feign:
  client:
    config:
      default:
        connectTimeout: 2000   # 2 seconds to establish connection
        readTimeout: 2000      # 2 seconds to wait for response        
